### ISSUE TITLE
prefix

### ISSUE THREAD

**Issue by Celllnside** [DeCoded-Void/Minesweeper_discord.py#1]
how do i set a prefix for the minesweeper?

**Comment by DeCoded-Void** [comment]
This script is a cog which makes it not standalone, it requires you to load it. If you are unfamiliar with discord.py and it's usage, please read the official docs at https://discordpy.readthedocs.io/

Some extra links that can help with understanding it:
https://discordpy.readthedocs.io/en/latest/ext/commands/cogs.html
https://gist.github.com/EvieePy/d78c061a4798ae81be9825468fe146be
